<a href="https://colab.research.google.com/github/Mallikarjun9741/DAV/blob/main/DAV_lab_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({
    "Order Date": [
        "2024-01-10",
        "2024-01-15",
        "2024-02-05",
        "2024-02-12",
        "2024-03-01",
        "2024-03-15",
        "2024-04-10",
        "2024-04-20",
        "2024-05-05",
        "2024-01-15",

    ],

    "Product Name":[
        "Laptop",
        "Mouse",
        "Printer",
        "Tablet",
        "Laptop",
        "Monitor",
        "Printer",
        "Smartwatch",
        "Mouse",
        "Mouse"
    ],

    "Category":[
        "Electronics",
        "Accessories",
        "Office",
        "Electronic",
        "Electronics",
        "Accessories",
        "Accessories",
        "Office",
        "Electronic",
        "Accessories"


    ],

    "Region": [
        "North",
        "South",
        "East",
        "West",
        "South",
        "North",
        "East",
        "West",
        "South",
        "North"

    ],

    "Quantity":[
        2,
        5,
        3,
        4,
        1,
        2,
        6,
        2,
        3,
        5

    ],
    "Sales": [
        50000,
        2500,
        9000,
        30000,
        55000,
        16000,
        3000,
        6000,
        45000,
        2500
    ],

    "Profit":[
        10000,
        500,
        1500,
        6000,
        11000,
        3000,
        None,
        1000,
        9000,
        500
    ]
})

print("1. ORGIONAL DATASET")
print("_"*50)
display(df)

1. ORGIONAL DATASET
__________________________________________________

   Order Date Product Name     Category Region  Quantity  Sales   Profit
0  2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South         5   2500    500.0
2  2024-02-05      Printer       Office   East         3   9000   1500.0
3  2024-02-12       Tablet   Electronic   West         4  30000   6000.0
4  2024-03-01       Laptop  Electronics  South         1  55000  11000.0
5  2024-03-15      Monitor  Accessories  North         2  16000   3000.0
6  2024-04-10      Printer  Accessories   East         6   3000      NaN
7  2024-04-20   Smartwatch       Office   West         2   6000   1000.0
8  2024-05-05        Mouse   Electronic  South         3  45000   9000.0
9  2024-01-15        Mouse  Accessories  North         5   2500    500.0

In [ ]:
print("2. FIRST 5 RECORDS")
print("_"*50)
display(df.head())

print("TAIL")
print("_"*50)
display(df.tail())

2. FIRST 5 RECORDS
__________________________________________________

   Order Date Product Name     Category Region  Quantity  Sales   Profit
0  2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1  2024-01-15        Mouse  Accessories  South         5   2500    500.0
2  2024-02-05      Printer       Office   East         3   9000   1500.0
3  2024-02-12       Tablet   Electronic   West         4  30000   6000.0
4  2024-03-01       Laptop  Electronics  South         1  55000  11000.0

TAIL
__________________________________________________

   Order Date Product Name     Category Region  Quantity  Sales  Profit
5  2024-03-15      Monitor  Accessories  North         2  16000  3000.0
6  2024-04-10      Printer  Accessories   East         6   3000     NaN
7  2024-04-20   Smartwatch       Office   West         2   6000  1000.0
8  2024-05-05        Mouse   Electronic  South         3  45000  9000.0
9  2024-01-15        Mouse  Accessories  North         5   2500   500.0

In [ ]:
print("3. DATASET SHAPE")
print("_"*50)
print(df.shape)

3. DATASET SHAPE
__________________________________________________
(10, 7)

In [ ]:
print("4. COLUMN NAMES")
print("_"*50)
print(df.columns)

4. COLUMN NAMES
__________________________________________________
Index(['Order Date', 'Product Name', 'Category', 'Region', 'Quantity', 'Sales',
       'Profit'],
      dtype='object')

In [ ]:
print("5. DATA TYPES")
print("_"*50)
print(df.dtypes)

5. DATA TYPES
__________________________________________________
Order Date       object
Product Name     object
Category         object
Region           object
Quantity          int64
Sales             int64
Profit          float64
dtype: object

In [ ]:
print("6. DESCRIPTIVE STATISTICS")
print("_"*50)
print(df.describe())

6. DESCRIPTIVE STATISTICS
__________________________________________________
        Quantity         Sales        Profit
count  10.000000     10.000000      9.000000
mean    3.300000  21900.000000   4722.222222
std     1.636392  21209.012759   4330.928820
min     1.000000   2500.000000    500.000000
25%     2.000000   3750.000000   1000.000000
50%     3.000000  12500.000000   3000.000000
75%     4.750000  41250.000000   9000.000000
max     6.000000  55000.000000  11000.000000

In [ ]:
print("7. MISSING VALUES ")
print("_"*50)
print(df.isnull().sum())

7. MISSING VALUES
__________________________________________________
Order Date      0
Product Name    0
Category        0
Region          0
Quantity        0
Sales           0
Profit          1
dtype: int64

In [ ]:
print("8. ROWS CONTAINNING MISSING VALUES ")
print("_"*50)
print(df[df.isnull().any(axis=1)])

8. ROWS CONTAINNING MISSING VALUES
__________________________________________________
   Order Date Product Name     Category Region  Quantity  Sales  Profit
6  2024-04-10      Printer  Accessories   East         6   3000     NaN

In [ ]:
print("9. TOTAL DUPLICANT RECORDS")
print("_"*50)
print(df.duplicated().sum())

9. TOTAL DUPLICANT RECORDS
__________________________________________________
0

In [ ]:
print("10. DUPLICANT RECORDS")
print("_"*50)
print(df[df.duplicated()])

10. DUPLICANT RECORDS
__________________________________________________
Empty DataFrame
Columns: [Order Date, Product Name, Category, Region, Quantity, Sales, Profit]
Index: []

In [ ]:
new_sales = pd.DataFrame({
    "Order Date": [
        "2024-06-01",
        "2024-06-05",
        "2024-06-10"
    ],
    "Product Name":[
        "Laptop",
        "Mouse",
        "Printer"
    ],
    "Category": [
        "Electronics",
        "Accessories",
        "Office"
    ],

    "Region": [
        "North",
        "South",
        "East"
    ],

    "Quantity":[
        2,
        4,
        3
    ],
    "Sales": [
        60000,
        2000,
        9000
    ],

    "Profit": [
        12000,
        400,
        1800
    ],

})
print("11. NEW SALES DATAFRAME")
print("_"*50)
display(new_sales)

11. NEW SALES DATAFRAME
__________________________________________________

   Order Date Product Name     Category Region  Quantity  Sales  Profit
0  2024-06-01       Laptop  Electronics  North         2  60000   12000
1  2024-06-05        Mouse  Accessories  South         4   2000     400
2  2024-06-10      Printer       Office   East         3   9000    1800

In [ ]:
combined_df = pd.concat(
    [df,new_sales],
    ignore_index=True
)

In [ ]:
print("12. CONCATENATED DATAFRAME")
print("_"*50)
display(combined_df)

12. CONCATENATED DATAFRAME
__________________________________________________

    Order Date Product Name     Category Region  Quantity  Sales   Profit
0   2024-01-10       Laptop  Electronics  North         2  50000  10000.0
1   2024-01-15        Mouse  Accessories  South         5   2500    500.0
2   2024-02-05      Printer       Office   East         3   9000   1500.0
3   2024-02-12       Tablet   Electronic   West         4  30000   6000.0
4   2024-03-01       Laptop  Electronics  South         1  55000  11000.0
5   2024-03-15      Monitor  Accessories  North         2  16000   3000.0
6   2024-04-10      Printer  Accessories   East         6   3000      NaN
7   2024-04-20   Smartwatch       Office   West         2   6000   1000.0
8   2024-05-05        Mouse   Electronic  South         3  45000   9000.0
9   2024-01-15        Mouse  Accessories  North         5   2500    500.0
10  2024-06-01       Laptop  Electronics  North         2  60000  12000.0
11  2024-06-05        Mouse  Accessories  South         4   2000    400.0
12  2024-06-10      Printer       Office   East         3   9000   1800.0

In [ ]:
product_info = pd.DataFrame({
    "Product Name": [
        "Laptop",
        "Mouse",
        "printer",
        "Tablet",
        "Monitor"
    ],
    "supplier":[
        "Dell",
        "Logitech",
        "HP",
        "Samsung",
        "LG"

    ],
    "Discount": [
        10,
        5,
        15,
        8,
        12
    ]

})

print("13. PRODUCT INFORMATION DATAFRAME")
print("_"*50)
display(product_info)

13. PRODUCT INFORMATION DATAFRAME
__________________________________________________

  Product Name  supplier  Discount
0       Laptop      Dell        10
1        Mouse  Logitech         5
2      printer        HP        15
3       Tablet   Samsung         8
4      Monitor        LG        12

In [ ]:
merged_df = pd.merge(
    df,
    product_info,
    on="Product Name",
    how="left"
)
print("14. MERGED DATAFRAME")
print("_"*50)
display(merged_df)

14. MERGED DATAFRAME
__________________________________________________

,Order Date,Product Name,Category,Region,Quantity,Sales,Profit,supplier,Discount
0,2024-01-10,Laptop,Electronics,North,2,50000,10000.0,Dell,10.0
1,2024-01-15,Mouse,Accessories,South,5,2500,500.0,Logitech,5.0
2,2024-02-05,Printer,Office,East,3,9000,1500.0,NaN,NaN
3,2024-02-12,Tablet,Electronic,West,4,30000,6000.0,Samsung,8.0
4,2024-03-01,Laptop,Electronics,South,1,55000,11000.0,Dell,10.0
5,2024-03-15,Monitor,Accessories,North,2,16000,3000.0,LG,12.0
6,2024-04-10,Printer,Accessories,East,6,3000,NaN,NaN,NaN
7,2024-04-20,Smartwatch,Office,West,2,6000,1000.0,NaN,NaN
8,2024-05-05,Mouse,Electronic,South,3,45000,9000.0,Logitech,5.0
9,2024-01-15,Mouse,Accessories,North,5,2500,500.0,Logitech,5.0

In [ ]:
region_info = pd.DataFrame(
    {
    "Region_Manager": [
    "Manager A",
    "Manager B",
    "Manager C",
    "Manager D"
    ]
    },
    index=[
        "North",
        "South",
        "East",
        "West"

    ]
)
print("15.  REGION INFORMATION DATAFRAME")
print("_"*50)
display(region_info)

15.  REGION INFORMATION DATAFRAME
__________________________________________________

      Region_Manager
North      Manager A
South      Manager B
East       Manager C
West       Manager D

In [ ]:
df_region=df.set_index("Region")
joined_df = df_region.join(region_info)
print("16. JOINED DATAFRAME")
print("_"*50)
display(joined_df)

16. JOINED DATAFRAME
__________________________________________________

,Order Date,Product Name,Category,Quantity,Sales,Profit,Region_Manager
Region,,,,,,,
North,2024-01-10,Laptop,Electronics,2,50000,10000.0,Manager A
South,2024-01-15,Mouse,Accessories,5,2500,500.0,Manager B
East,2024-02-05,Printer,Office,3,9000,1500.0,Manager C
West,2024-02-12,Tablet,Electronic,4,30000,6000.0,Manager D
South,2024-03-01,Laptop,Electronics,1,55000,11000.0,Manager B
North,2024-03-15,Monitor,Accessories,2,16000,3000.0,Manager A
East,2024-04-10,Printer,Accessories,6,3000,NaN,Manager C
West,2024-04-20,Smartwatch,Office,2,6000,1000.0,Manager D
South,2024-05-05,Mouse,Electronic,3,45000,9000.0,Manager B
North,2024-01-15,Mouse,Accessories,5,2500,500.0,Manager A

In [ ]:
region_sales = df.groupby(
    "Region"
)["Sales"].sum()
print("17. TOTAL SALES BY REGION " )
print("_"*50)
display(region_sales)

17. TOTAL SALES BY REGION
__________________________________________________

Region
East      12000
North     68500
South    102500
West      36000
Name: Sales, dtype: int64

In [ ]:
pivot_table = pd.pivot_table(
    df,
    values="Sales",
    index="Category",
    columns="Region",
    aggfunc="sum",
    fill_value=0
)
print("18  PIVOT TABLE.")
print("_"*50)
display(pivot_table)

18  PIVOT TABLE.
__________________________________________________

Region       East  North  South   West
Category
Accessories  3000  18500   2500      0
Electronic      0      0  45000  30000
Electronics     0  50000  55000      0
Office       9000      0      0   6000